# -*- coding: utf-8 -*-
"""Exp8_GraphSegmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwry7B5qLzldy1pSWQVifPaNzvBn0WOu
"""

from skimage.segmentation import felzenszwalb
import matplotlib.pyplot as plt

from sklearn.datasets import load_sample_image
china = load_sample_image('china.jpg')

plt.imshow(china);
plt.show()

segmented_img= felzenszwalb(china, scale=100, sigma=0.5, min_size=50)
plt.imshow(segmented_img,cmap='nipy_spectral')
plt.show()

segmented_img= felzenszwalb(china, scale=500, sigma=0.8, min_size=100)
plt.imshow(segmented_img,cmap='nipy_spectral')
plt.show()

scale=[100,500,1000,5000]
sigma=[0.2,0.5,1.0,2.0]
min_size=[100,500]

for ms in min_size:
    print("For min_size: ",ms)
    fig, axes = plt.subplots(nrows=len(scale), ncols=len(sigma), figsize=(22,16))
    for i, sc in enumerate(scale):
        for j, sig in enumerate(sigma):
            segmented_img= felzenszwalb(china, scale=sc, sigma=sig, min_size=ms)
            axes[i,j].imshow(segmented_img,cmap='nipy_spectral')
            axes[i,j].set_title("scale: "+str(sc)+" sigma: "+str(sig))
    plt.show()